name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [lts/*]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: test 
      run: |
           npm install
           npm test
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: cobertura-coverage.xml
          directory: ./coverage
          fail_ci_if_error: true
          verbose: true

    - name: Upload coverage reports to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
        fail-on-error: true
        debug: true
        measure: true            
